version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: jubilut_db
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - jubilut-network
    ports:
      - "5432:5432"

  api:
    build: ./api
    container_name: jubilut_api
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./api:/var/www/html
    networks:
      - jubilut-network
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: jubilut_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./api:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - jubilut-network
    depends_on:
      - api

  front:
    build: ./front
    container_name: jubilut_front
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./front:/app
      - /app/node_modules
    networks:
      - jubilut-network

networks:
  jubilut-network:
    driver: bridge

volumes:
  db_data:
